<a href="https://colab.research.google.com/github/tanya-romanova/ml_course_pylieva/blob/main/HW_2_1_Matrices%20and%20vectors%20(linear%20algebra%20intro).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [30]:
import numpy as np
import random as rnd

# v_rand = np.array([rnd.uniform(0, 1) for i in range(10)])
vector = np.random.rand(10)

print(vector, vector.shape, sep='\n')
print()

matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print(matrix, matrix.shape, sep='\n')

[0.22840882 0.1994599  0.79235136 0.36702818 0.73083759 0.26101668
 0.01419252 0.36726965 0.51543044 0.10113632]
(10,)

[[11 14 17]
 [20 23 26]
 [29 32 35]]
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [32]:
vector = np.round(vector + 10, 2)
print(vector)
print()

matrix = matrix * 2
print(matrix)
print()

vector1 = vector**2
print(vector1)

[20.23 20.2  20.79 20.37 20.73 20.26 20.01 20.37 20.52 20.1 ]

[[ 44  56  68]
 [ 80  92 104]
 [116 128 140]]

[409.2529 408.04   432.2241 414.9369 429.7329 410.4676 400.4001 414.9369
 421.0704 404.01  ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [44]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [45]:
result_matrix = np.dot(B, A)
print(result_matrix)
print()

result_matrix1 = np.dot(result_matrix, C)      # extract 2nd col
print(result_matrix1)
print()

result_matrix2 = np.dot(D, result_matrix)      # swap rows
print(result_matrix2)


[[0.7281 0.5202]
 [0.2034 0.2846]]

[[0.5202]
 [0.2846]]

[[0.2034 0.2846]
 [0.7281 0.5202]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [56]:
print(result_matrix.T)
print()

print(vector)
print(vector.shape)
print()
print(vector.T)   # зміни не бачу!
print(vector.T.shape)
print()

column_vector = np.expand_dims(vector, axis=1)
print(column_vector)    # транспонований порівняно з vector
print(column_vector.shape)
print()
print(column_vector.T)  # транспонований порівняно з column_vector
print(column_vector.T.shape)

[[0.7281 0.2034]
 [0.5202 0.2846]]

[20.23 20.2  20.79 20.37 20.73 20.26 20.01 20.37 20.52 20.1 ]
(10,)

[20.23 20.2  20.79 20.37 20.73 20.26 20.01 20.37 20.52 20.1 ]
(10,)

[[20.23]
 [20.2 ]
 [20.79]
 [20.37]
 [20.73]
 [20.26]
 [20.01]
 [20.37]
 [20.52]
 [20.1 ]]
(10, 1)

[[20.23 20.2  20.79 20.37 20.73 20.26 20.01 20.37 20.52 20.1 ]]
(1, 10)
